# Generated by Django 3.0.8 on 2021-01-29 13:45

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Позиция')),
                ('company', models.CharField(max_length=40, verbose_name='Kомпания')),
                ('type_work', models.CharField(max_length=100, verbose_name='Вид занятости')),
                ('town', models.CharField(max_length=15, verbose_name='Местоположение')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=30, verbose_name='Почта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('offer', models.TextField(verbose_name='Мы предлагаем')),
                ('salary', models.CharField(blank=True, max_length=20, verbose_name='Заработная плата')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=15, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', inverse_match='True', message='could not be space', regex='/w')], verbose_name='Позиция')),
                ('town', models.CharField(blank=True, max_length=15, verbose_name='Местоположение')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=30, verbose_name='Почта')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('experience', models.TextField(validators=[blog.models.validate_space], verbose_name='Опыт работы')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('education', models.TextField(verbose_name='Образование')),
                ('type_work', models.TextField(verbose_name='Вид занятости')),
                ('addition', models.TextField(blank=True, verbose_name='Дополнительно')),
                ('salary', models.CharField(blank=True, max_length=20, verbose_name='Заработная плата')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('user', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
