# Generated by Django 3.0.8 on 2021-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210126_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
    ]
