# Generated by Django 3.0.8 on 2020-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
