# Generated by Django 3.0.8 on 2020-10-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='passsword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='tipe_work',
            new_name='type_work',
        ),
    ]
