# Generated by Django 3.0.8 on 2020-10-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201023_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='Responsibilities',
            new_name='responsibilities',
        ),
    ]
