# Generated by Django 3.0.8 on 2020-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201023_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='password',
            field=models.EmailField(max_length=20, verbose_name='Пароль авторизации на сайте'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type_work',
            field=models.CharField(max_length=400, verbose_name='Вид занятости'),
        ),
    ]
