# Generated by Django 3.0.8 on 2020-10-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201026_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='achievements',
            field=models.TextField(blank=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type_work',
            field=models.TextField(verbose_name='Вид занятости'),
        ),
    ]
