# Generated by Django 3.0.8 on 2020-10-27 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201026_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='password',
            field=models.EmailField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
