# Generated by Django 3.0.8 on 2020-10-27 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201027_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
