# Generated by Django 3.0.8 on 2020-11-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201027_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(blank=True, max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.CharField(max_length=40, verbose_name='Kомпания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='password',
            field=models.EmailField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type_work',
            field=models.CharField(max_length=100, verbose_name='Вид занятости'),
        ),
    ]
