# Generated by Django 3.0.8 on 2020-11-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201101_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
    ]
