# Generated by Django 3.0.8 on 2020-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201101_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Почта'),
        ),
    ]
