# Generated by Django 3.0.8 on 2020-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201102_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='salary',
            field=models.CharField(default='не указана', max_length=20, verbose_name='Заработная плата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(default='не указана', max_length=20, verbose_name='Заработная плата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='town',
            field=models.CharField(blank=True, max_length=15, verbose_name='Местоположение'),
        ),
    ]
