# Generated by Django 3.0.8 on 2020-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201104_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(verbose_name='Навыки'),
        ),
    ]
